### ISSUE TITLE
cat_io_uring: unused variable 'offset'

### ISSUE THREAD

**Issue by pbruenn** [shuveb/loti-examples#2]
I got confused by this offset, because it was incremented before the buffer was allocated. But when I looked closer, I didn't find any place where it's used. So maybe you want to drop it entirely:
https://github.com/shuveb/loti-examples/blob/e5fb3f595063d14bc4569e4154f82e781ab2ee08/cat_io_uring.c#L227
https://github.com/shuveb/loti-examples/blob/e5fb3f595063d14bc4569e4154f82e781ab2ee08/cat_io_uring.c#L251

**Comment by shuveb** [comment]
Awesome catch! Thanks. This has now been fixed.
