### ISSUE TITLE
A few bugs in cat_io_uring.c

### ISSUE THREAD

**Issue by BigBigos** [shuveb/loti-examples#3]
Hello.

I did not really build & test `cat_io_uring.c`, but by inspection I have found a couple of (possible) bugs. Please be aware that I might have just misunderstood the intention of the code.

https://github.com/shuveb/loti-examples/blob/5193a22775e9263d983986fe3f631ad9d947d202/cat_io_uring.c#L203

I believe it should be `fi->iovecs[i].iov_base` instead of `fi->iovecs->iov_base`.

https://github.com/shuveb/loti-examples/blob/5193a22775e9263d983986fe3f631ad9d947d202/cat_io_uring.c#L232

I don't think such a `malloc()` works correctly, as the `struct file_info` has an unsized array at the end. It should probably be something like:

```
fi = malloc(sizeof(*fi) + sizeof(struct iovec) * blocks);
```

Also, `free()` is not called on neither `submitter`, `fi` nor the `iovecs`, though that could be explained as simplifying the example.

**Comment by shuveb** [comment]
You are indeed a human C compiler, @BigBigos! :clap: 
I've fixed the first 2 issues you've pointed out. Since this is a short-lived program, I'll just let the operating system clean up the allocated memory to keep the example simple. 
Thanks a lot indeed!
